name = "subscription"
main = "index.ts"
compatibility_date = "2026-06-06"

[[kv_namespaces]]
binding = "CONFIG_KV"
id = "bae78c3c784b4d74b7f7e39388b1e680"

[vars]
ADMIN_USER = "admin"
# Set ADMIN_PASSWORD with `wrangler secret put ADMIN_PASSWORD`.

[[rules]]
type = "Text"
globs = ["**/*.yaml", "**/*.yml"]
fallthrough = true
